### ISSUE TITLE
no datepicker shown for DateField

### ISSUE THREAD

**Issue by marianobrc** [sarendsen/django-slick#1]
@sarendsen 
I'm using django-sclick 1.2 for the admin, with django 1.9.
My model has a DateField but is shown as a text box on the admin.

my model:
![slick_menu_code](https://cloud.githubusercontent.com/assets/9864478/15324085/5317649e-1c1b-11e6-92de-82fc3c6a23ce.png)

my admin class:
![slick_menu_admin_code](https://cloud.githubusercontent.com/assets/9864478/15324048/2695901c-1c1b-11e6-8a84-b0c4334cecdc.png)

Admin UI
![slick_datepicker](https://cloud.githubusercontent.com/assets/9864478/15323953/b6be1ea8-1c1a-11e6-9f2d-4a9b257cd7d8.png)

Slick is the best responsive app for the admin working with django 1.9 anyway.
Thanks!

**Comment by lostb1t** [comment]
Django Slick does not include a 'datepicker'. It uses the default widget for django which is just a text input. Implementing it isn't so hard though, with all the free js datepicker plugins around. I would also be open for a pull request.

**Comment by marianobrc** [comment]
Hi @sarendsen, thanks for your answer. I think that slick is great, I've tested lot of other responsive UIs for the admin and this one is the best one to me. I'll try to add the datepicker and send a pull request.

**Comment by marianobrc** [comment]
Hi @sarendsen I've forked the repo at the master branch and I'm trying run it on it's current version (1.9) but I'm having some troubles to get it working. If i install the release 1.2 it works straightforward, but if i install the last version from the master branch i see the admin UI just as original django admin UI.
I'm wondering if is any new dependency since version 1.2?

Thanks

**Comment by lostb1t** [comment]
tnx for the headsup. Im using the master branch myself but i might screwed it up a bit. Ill put in some work tomorrow to make it work again.
